#!/bin/bash
#PBS -N Finetune_VAE
#PBS -q gpu
#PBS -l select=1:host=node9:ncpus=1:ngpus=1
#PBS -o /storage/users/mahesh/Mafaz/Projects/CFD_DiT/VAE_Lid_driven.out
#PBS -e /storage/users/mahesh/Mafaz/Projects/CFD_DiT/VAE_Lid_driven.err

cd "$PBS_O_WORKDIR"

source $USER_DIR/Mafaz/myenv/bin/activate

export CUDA_VISIBLE_DEVICES="$NODE9_MIG_UUID"

echo "Job started on $(hostname) at $(date)"
python3 -m training.train_vae.training
echo "Job finished at $(date)"